#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S3, HTServo,  HTServo,  none,     none)
#pragma config(Sensor, S1,     motors,         sensorNone)
#pragma config(Sensor, S2,     SMUX,           sensorI2CCustom9V)
#pragma config(Sensor, S3,     servos,         sensorNone)
#pragma config(Motor,  motorA,          flagMotor,     tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     leftFrontMotor, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     leftRearMotor, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     rightFrontMotor, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     rightRearMotor, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     spinnerMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     liftMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     rightWinch,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     leftWinch,     tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S3_C1_1,    leftHook,             tServoStandard)
#pragma config(Servo,  srvo_S3_C1_2,    rightHook,            tServoStandard)
#pragma config(Servo,  srvo_S3_C1_3,    unusedS3C13,          tServoStandard)
#pragma config(Servo,  srvo_S3_C1_4,    unusedS3C14,          tServoStandard)
#pragma config(Servo,  srvo_S3_C1_5,    unusedS3C15,          tServoStandard)
#pragma config(Servo,  srvo_S3_C1_6,    unusedS3C16,          tServoStandard)
#pragma config(Servo,  srvo_S3_C2_1,    leftHopper,           tServoStandard)
#pragma config(Servo,  srvo_S3_C2_2,    rightHopper,          tServoStandard)
#pragma config(Servo,  srvo_S3_C2_3,    unusedS3C23,          tServoStandard)
#pragma config(Servo,  srvo_S3_C2_4,    unusedS3C24,          tServoStandard)
#pragma config(Servo,  srvo_S3_C2_5,    unusedS3C25,          tServoStandard)
#pragma config(Servo,  srvo_S3_C2_6,    unusedS3C26,          tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*///////////////////////////////
Ingraham High School Robotics
FTC Team #7462
Main Robot Code
/*///////////////////////////////
#pragma debuggerWindows("joystickSimple");
#include "drivers/hitechnic-sensormux.h"
#include "drivers/lego-light.h"
#include "JoystickDriver.c"

///// Sensor Multiplexer Interface /////
const tMUXSensor sonar = msensor_S2_1;
const tMUXSensor IRSeeker = msensor_S2_2;
const tMUXSensor lightRight = msensor_S2_3;
const tMUXSensor lightLeft = msensor_S2_4;

const int SERVO_ADJUST = 1;
int leftHookVal = 0;
int rightHookVal = 0;
int leftHopperVal = 0;
int rightHopperVal = 0;

void SetHookServo(int leftTarget, int rightTarget)
{
	servo[leftHook] = leftTarget;
	servo[rightHook] = rightTarget;
}

void SetHopperServo(int leftTarget, int rightTarget)
{
	servo[leftHopper] = leftTarget;
	servo[rightHopper] = rightTarget;
}

////////////////////////////////
///// ROBOT INITIALIZATION /////
#include "MainIncludes.c";


//////////////////////
///// DRIVE TASK /////
task Drive()
{
	//Integer variable that allows you to specify a "deadzone" where values (both positive or negative)
	//less than the threshold will be ignored.
	int threshold = 10;
	while(true)
	{
		//Get the Latest joystick values
		getJoystickSettings(joystick);
		// Tank Drive Uses Both Left and Right Analog Sticks //
		if(abs(joystick.joy1_y1) > threshold){
			motor[leftFrontMotor] = joystick.joy1_y1;
			motor[leftRearMotor] = joystick.joy1_y1;
		}	else {
			motor[leftFrontMotor] = 0;
			motor[leftRearMotor] = 0;
		}
		if(abs(joystick.joy1_y2) > threshold) {
			motor[rightFrontMotor] = joystick.joy1_y2;
			motor[rightRearMotor] = joystick.joy1_y2;
		} else {
			motor[rightFrontMotor] = 0;
			motor[rightRearMotor] = 0;
		}
	}
}

task main()
{
  initializeRobot();
  //waitForStart(); // Wait for the beginning of autonomous phase.

  //StartTask(Drive);

  int threshold = 10;
	//Loop Forever
	while(true)
	{
		//Get the Latest joystick values
		getJoystickSettings(joystick);
		leftHookVal = ServoValue[leftHook];
		rightHookVal = ServoValue[rightHook];
		leftHopperVal = servo[leftHopper];
		rightHopperVal = servo[rightHopper];
		if(joy1Btn(2) == 1) // A
		{
			SetHopperServo(100,100);
		}
		else if(joy1Btn(3) == 1) // B
		{
			SetHopperServo(200,200); // put away
		}
		else if(joy1Btn(6) == 1) // R1
		{
			int s = ServoValue[leftHopper]+10;
			SetHopperServo(s,s);
			while(joy1Btn(6)==1)
			{}
		}
		else if(joy1Btn(5) ==1) // L1
		{
			int s = ServoValue[leftHopper]-10;
			SetHopperServo(s,s);
			while(joy1Btn(5)==1)
			{}
		}

		if(joy1Btn(1) == 1) // X
		{
			SetHookServo(100,255-100);
		}
		else if(joy1Btn(4) == 1) // Y
		{
			SetHookServo(200,255-200); //
		}
		else if(joy1Btn(7) == 1) // R2
		{
			int sleft = ServoValue[leftHook]+10;
			int sright = 255-sleft;
			SetHookServo(sleft,sright);
			while(joy1Btn(7)==1)
			{}
		}
		else if(joy1Btn(8) ==1) // L2
		{
			int sleft = ServoValue[leftHook]-10;
			int sright = 255-sleft;
			SetHookServo(sleft,sright);
			while(joy1Btn(8)==1)
			{}
		}

		if(joy1Btn(10) == 1)
			initializeRobot();
	}
}
