#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S3, HTServo,  HTServo,  none,     none)
#pragma config(Sensor, S1,     motors,         sensorNone)
#pragma config(Sensor, S2,     SMUX,           sensorI2CCustom9V)
#pragma config(Sensor, S3,     servos,         sensorNone)
#pragma config(Motor,  motorA,          flagMotor,     tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     leftFrontMotor, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     leftRearMotor, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     rightFrontMotor, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     rightRearMotor, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     spinnerMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     liftMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     rightWinch,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     leftWinch,     tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S3_C1_1,    leftHook,             tServoStandard)
#pragma config(Servo,  srvo_S3_C1_2,    rightHook,            tServoStandard)
#pragma config(Servo,  srvo_S3_C1_3,    unusedS3C13,          tServoStandard)
#pragma config(Servo,  srvo_S3_C1_4,    unusedS3C14,          tServoStandard)
#pragma config(Servo,  srvo_S3_C1_5,    unusedS3C15,          tServoStandard)
#pragma config(Servo,  srvo_S3_C1_6,    unusedS3C16,          tServoStandard)
#pragma config(Servo,  srvo_S3_C2_1,    leftHopper,           tServoStandard)
#pragma config(Servo,  srvo_S3_C2_2,    rightHopper,          tServoStandard)
#pragma config(Servo,  srvo_S3_C2_3,    unusedS3C23,          tServoStandard)
#pragma config(Servo,  srvo_S3_C2_4,    unusedS3C24,          tServoStandard)
#pragma config(Servo,  srvo_S3_C2_5,    unusedS3C25,          tServoStandard)
#pragma config(Servo,  srvo_S3_C2_6,    unusedS3C26,          tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*///////////////////////////////
Ingraham High School Robotics
FTC Team #7462
Main Robot Code
/*///////////////////////////////
#pragma debuggerWindows("joystickSimple");
#include "drivers/hitechnic-sensormux.h"
#include "drivers/lego-light.h"
#include "JoystickDriver.c"

///// CONSTANTS /////
#define FULL_IMPULSE (100)
#define HALF_IMPULSE (50)
#define QUARTER_IMPULSE (25)
#define EIGHTH_IMPULSE (12)
const int TEST_IMPULSE = 50;

///// Sensor Multiplexer Interface /////
const tMUXSensor sonar = msensor_S2_1;
const tMUXSensor IRSeeker = msensor_S2_2;
const tMUXSensor lightRight = msensor_S2_3;
const tMUXSensor lightLeft = msensor_S2_4;

////////////////////////////////
///// ROBOT INITIALIZATION /////
void initializeRobot()
{

	// Initialize Motor Encoders //
	nMotorEncoder[leftRearMotor] = 0;

	// Stop All Motors //
	motor[leftFrontMotor] = 0;
	motor[leftRearMotor] = 0;
	motor[rightFrontMotor] = 0;
	motor[rightRearMotor] = 0;
	motor[spinnerMotor] = 0;

	// Cycle Light Sensor Lights //
	// Indicates Initialization Complete //
	int delay = 50;
	for(int i=0; i<10; i++)
	{
		LSsetInactive(lightRight);
  	LSsetInactive(lightLeft);
		wait1Msec(delay);
	  LSsetActive(lightRight);
  	LSsetActive(lightLeft);
		wait1Msec(delay);
	}

	return;
}

void DriveLeftSide(int power)
{
	motor[leftFrontMotor] = power;
	motor[leftRearMotor] = power;
}

void DriveRightSide(int power)
{
	motor[rightFrontMotor] = power;
	motor[rightRearMotor] = power;
}

void DriveSpinnerMotor(int power)
{
	motor[spinnerMotor] = power;
}

void DriveFlagMotor(int power)
{
	motor[flagMotor] = power;
}

void DriveWinchMotors(int power)
{
	motor[leftWinch] = power;
	motor[rightWinch] = power;
}

void DriveHookServos(int power)
{
	servo[leftHook] = power;
	servo[rightHook] = power;
}

void DriveHopperServos(int power)
{
	servo[leftHopper] = power;
	servo[rightHopper] = power;
}

void DriveLiftMotor(int power)
{
	motor[liftMotor] = power;
}

//////////////////////
///// DRIVE TASK /////
task Drive()
{
	while(true)
	{
		//Integer variable that allows you to specify a "deadzone" where values (both positive or negative)
		//less than the threshold will be ignored.
		int threshold = 10;
		//Get the Latest joystick values
		getJoystickSettings(joystick);

		//Each of these passes a value to set the motors to under certain circumstances
		//Left Wheels
		if(abs(joystick.joy1_y1) > threshold){
			DriveLeftSide(joystick.joy1_y1);
		}
		else {
			DriveLeftSide(0);
		}
		//Right Wheels
		if(abs(joystick.joy1_y2) > threshold) {
			DriveRightSide(joystick.joy1_y2);
		}
		else {
			DriveRightSide(0);
		}
		//Spinner
		if(abs(joystick.joy2_y1) > threshold) {
			DriveSpinnerMotor(joystick.joy2_y1);
		}
		else {
			DriveSpinnerMotor(0);
		}
		//Flag
		if(joystick.joy2_y2 > threshold) {
			DriveFlagMotor(joystick.joy2_y2);
		}
		else {
			DriveFlagMotor(0);
		}
		//Winches
		if(joy2Btn(6) == 1) {
			DriveWinchMotors(TEST_IMPULSE);
		}
		else if(joy2Btn(8) == 1) {
			DriveWinchMotors(-TEST_IMPULSE);
		}
		else {
			DriveWinchMotors(0);
		}
		//Hooks
		if(joy2Btn(5) == 1) {
			DriveHookServos(TEST_IMPULSE);
		}
		else if(joy2Btn(7) == 1) {
			DriveHookServos(-TEST_IMPULSE);
		}
		else {
			DriveHookServos(0);
		}
		//Hoppers
		if(joy2Btn(1) == 1) {
			DriveHopperServos(TEST_IMPULSE);
		}
		else if(joy2Btn(2) == 1) {
			DriveHopperServos(-TEST_IMPULSE);
		}
		else {
			DriveHopperServos(0);
		}
		//Lift
		if(joy2Btn(4) == 1) {
			DriveLiftMotor(TEST_IMPULSE);
		}
		else if(joy2Btn(3) == 1) {
			DriveLiftMotor(-TEST_IMPULSE);
		}
		else {
			DriveLiftMotor(0);
		}
	}
}

task main()
{
  initializeRobot();
  //waitForStart(); // Wait for the beginning of autonomous phase.

  StartTask(Drive);

  int threshold = 10;
	/* Not really sure what this loop is here for, going to leave it in just in case
	while(true)
	{
	}
	*/
}
