#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IRSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorA,          gripperMotor,  tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     rightMotor,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotor,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     flagMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     spinnerMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     liftLeftMotor, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     liftRightMotor, tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*///////////////////////////////
Ingraham High School Robotics
FTC Team #7462
Main Robot Code
/*///////////////////////////////
#pragma debuggerWindows("joystickSimple");
#include "JoystickDriver.c"

/////////////////////
///// CONSTANTS /////
const int fullImpulse = 100;
const int halfImpulse = 50;
const int quarterImpulse = 25;
const int eighthImpulse = 12;
int IR_out = 0;
int Sonar_out = 0;
int Light_out = 0;
int motorEncoder_out = 0;

//Integer variable that allows you to specify a "deadzone" where values (both positive or negative)
//less than the threshold will be ignored.
int threshold = 10;

////////////////////////////////
///// ROBOT INITIALIZATION /////
void initializeRobot()
{
  // Place code here to initialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
	wait1Msec(1000);
  return;
}

//////////////////////
///// DRIVE TASK /////
task Drive()
{
	while(true)
	{
		//Get the Latest joystick values
		getJoystickSettings(joystick);
		// Tank Drive Uses Both Left and Right Analog Sticks //
		if(abs(joystick.joy1_y1) > threshold)
			motor[leftMotor] = joystick.joy1_y1;
		else
			motor[leftMotor] = 0;
		if(abs(joystick.joy1_y2) > threshold)
			motor[rightMotor] = joystick.joy1_y2;
		else
			motor[rightMotor] = 0;
	}
}

void MoveFlagMotor(const int speed, const int time)
{
	motor[flagMotor] = speed;
	if(time > 0)
		wait1Msec(time);
}

void MoveLiftMotor(const int speed, const int time)
{
	motor[liftLeftMotor] = speed;
	motor[liftRightMotor] = speed;
	if(time > 0)
		wait1Msec(time);
}

/////////////////////
///// MAIN TASK /////
task main()
{
  initializeRobot();
  //waitForStart(); // Wait for the beginning of autonomous phase.

  StartTask(Drive);

	//Loop Forever
	while(true)
	{
		// Sensor Calibration //
		IR_out = SensorValue[IRSeeker];
		Sonar_out = SensorValue[sonar];
		Light_out = SensorValue[light];
		motorEncoder_out = nMotorEncoder[leftMotor];

		//Get the Latest joystick values
		getJoystickSettings(joystick);

		//Flag Motor Control //
		if(joy1Btn(8) == 1)       // XBox A
		{
			MoveFlagMotor(-fullImpulse,-1); // raise the flag
		}
		else if(joy1Btn(7) == 1)  // XBox B
		{
			MoveFlagMotor(fullImpulse,-1);  // lower the flag
		}
		else
		{
			MoveFlagMotor(0,-1);    // stop the flag motor
		}

		// Lift Motor Control //
		if(joy1Btn(5) == 1 )
		{
			MoveLiftMotor(fullImpulse,-1);
		}
		else if(joy1Btn(6) == 1 )
		{
			MoveLiftMotor(-fullImpulse,-1);
		}
		else
		{
			MoveLiftMotor(0,-1);
		}
	}
}
