#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IRSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorA,          gripperMotor,  tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     rightMotor,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotor,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     flagMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     spinnerMotor,  tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
IR Seeker Sample File
Assumes IR Seeker is plugged into Sensor Port #2.
IR Seeker spits out a value between 0 and 9.
 - 0 - No IR Detected
 - 1 - Left
 - 2 -
 - 3 -
 - 4 -
 - 5 - Middle
 - 6 -
 - 7 -
 - 8 -
 - 9 - Right
 ----------------------------------------------------------------------------------------------------*/
#include "JoystickDriver.c"

// Global LightValue Variable //
int irValue = 0;

task main()
{
	while(1==1)
	{
		// Light Sensor Read //
		irValue = SensorValue[IRSeeker];

		// Basic Tank Drive //
		getJoystickSettings(joystick);
		if(abs(joystick.joy1_y1) > 10)
			motor[leftMotor] = joystick.joy1_y1;
		else
			motor[leftMotor] = 0;

		if(abs(joystick.joy1_y2) > 10)
			motor[rightMotor] = joystick.joy1_y2;
		else
			motor[rightMotor] = 0;
	}
}
