#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IRSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorA,          gripperMotor,  tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     rightMotor,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotor,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     flagMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     spinnerMotor,  tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
Light Sensor Sample File
Run this file with the Gripper Bot in RVW and watch the Global Variable "ligthValue" so you can
calibrate the light sensor. The light sensor will put out a value between 0 and 100.
 - 100 is full reflection - like white
 - 0 is no reflection - like black
Assumes Light Sensor is plugged into Sensor Port #3.
----------------------------------------------------------------------------------------------------*/
#include "JoystickDriver.c"

// Global LightValue Variable //
int lightValue = 0;

task main()
{
	while(1==1)
	{
		// Light Sensor Read //
		lightValue = SensorValue[light];

		// Basic Tank Drive //
		getJoystickSettings(joystick);
		if(abs(joystick.joy1_y1) > 10)
			motor[leftMotor] = joystick.joy1_y1;
		else
			motor[leftMotor] = 0;

		if(abs(joystick.joy1_y2) > 10)
			motor[rightMotor] = joystick.joy1_y2;
		else
			motor[rightMotor] = 0;
	}
}
