#pragma config(Sensor, S1,     sensor_mux,     sensorI2CCustom9V)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++*/
#include "../drivers/hitechnic-sensormux.h"
#include "../drivers/hitechnic-irseeker-v2.h"
#include "../drivers/lego-touch.h"
#include "../drivers/lego-light.h"

// Sensor Read Variables //
int touch1_out = 0;
int touch2_out = 0;
int touch3_out = 0;
int light_out = 0;

// SMUX Interface //
const tMUXSensor S_TOUCH1 = msensor_S1_1;
const tMUXSensor S_TOUCH2 = msensor_S1_2;
const tMUXSensor S_TOUCH3 = msensor_S1_3;
const tMUXSensor S_LIGHT = msensor_S1_4;


// Main Task
// This runs first
task main()
{
	// Turn Light Sensor Light On //
  LSsetActive(S_LIGHT);

  while(true)
  {
		touch1_out = LSvalNorm(S_TOUCH1);
		touch2_out = LSvalNorm(S_TOUCH2);
		touch3_out = LSvalNorm(S_TOUCH3);
  	light_out = LSvalNorm(S_LIGHT);
	}

}
