#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     rightMotor,    tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotor,     tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(Tetrix)

void proportionalMotorControl(const int nPower, const int nDirection, const int nTime)
{
  if (nDirection < 0)
  {
    // Turn left

    motor[rightMotor] = nPower;
    motor[leftMotor]  = nPower * (50 + nDirection) / 50;
  }
  else
  {
    // Turn right

    motor[leftMotor]  = nPower;
    motor[rightMotor] = nPower * (50 - nDirection) / 50;
  }
  wait1Msec(nTime);
}

#define goForward(nTime)    proportionalMotorControl(75,    0, nTime)
#define turnRight(nTime)    proportionalMotorControl(75,   50, nTime)
#define turnLeft(nTime)     proportionalMotorControl(75,  -50, nTime)
#define goBackwards(nTime)  proportionalMotorControl(-75,   0, nTime)

task main()
{
  goForward(2000);
  turnLeft(1000);
  goForward(2000);
  turnRight(500);
  goForward(500);
  goBackwards(3000);
}
