#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S3, HTServo,  HTServo,  none,     none)
#pragma config(Sensor, S1,     motors,         sensorNone)
#pragma config(Sensor, S2,     SMUX,           sensorI2CCustom9V)
#pragma config(Sensor, S3,     servos,         sensorNone)
#pragma config(Sensor, S4,     gyroSensor,     sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorA,          flagMotorA,    tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          flagMotorB,    tmotorNXT, openLoop, reversed, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     leftFrontMotor, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     leftRearMotor, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     rightFrontMotor, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     rightRearMotor, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     spinnerMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     liftMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     rightWinch,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     leftWinch,     tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S3_C1_1,    leftHook,             tServoStandard)
#pragma config(Servo,  srvo_S3_C1_2,    rightHook,            tServoStandard)
#pragma config(Servo,  srvo_S3_C1_3,    unusedS3C13,          tServoStandard)
#pragma config(Servo,  srvo_S3_C1_4,    unusedS3C14,          tServoStandard)
#pragma config(Servo,  srvo_S3_C1_5,    unusedS3C15,          tServoStandard)
#pragma config(Servo,  srvo_S3_C1_6,    unusedS3C16,          tServoStandard)
#pragma config(Servo,  srvo_S3_C2_1,    leftHopper,           tServoStandard)
#pragma config(Servo,  srvo_S3_C2_2,    rightHopper,          tServoStandard)
#pragma config(Servo,  srvo_S3_C2_3,    unusedS3C23,          tServoStandard)
#pragma config(Servo,  srvo_S3_C2_4,    unusedS3C24,          tServoStandard)
#pragma config(Servo,  srvo_S3_C2_5,    unusedS3C25,          tServoStandard)
#pragma config(Servo,  srvo_S3_C2_6,    unusedS3C26,          tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../Sensors/gyro.c"
#define GYRO_OVERRUN (16.0)
#define GYRO_SPEED (50)

void turnToDegree(int target) {
	// Turn left or right
	int speed = GYRO_SPEED;
	if (target < 0) {
		speed *= -1;
	}

	// Offset the target by our expected overrun
	if (target < 0) {
		target += GYRO_OVERRUN;
	} else {
		target -= GYRO_OVERRUN;
	}

	// Turn to the target
	int angle = 0;
	motor[flagMotorA] = speed;
	resetGyro();
	while (abs(angle) < abs(target)) {
		angle = (int)readGyro();
	}
	motor[flagMotorA] = 0;
}

///// MAIN TASK /////
task main() {

	// Start the gyro and wait for it to settle
	StartTask(gyro);
	while (!GYRO_READY) {
		wait1Msec(5);
	}

	// Turn 90 clockwise
	turnToDegree(90);

	// Turn 45 anti-clockwise
	wait1Msec(500);
	turnToDegree(-45);

	// Turn 45 anti-clockwise
	wait1Msec(500);
	turnToDegree(-45);

	// Turn 180 aclockwise
	wait1Msec(500);
	turnToDegree(180);

	// Turn 90 anti-clockwise
	wait1Msec(500);
	turnToDegree(-90);

	// Turn 90 anti-clockwise
	wait1Msec(500);
	turnToDegree(-90);
}
