#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IRSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorA,          gripperMotor,  tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     rightMotor,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotor,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     armMotor,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     spinnerMotor,  tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
MODIFICATION:
This program has been modified in the following manner:
1. It works with an XBox Controller.
2. Arcade Drive is the default drive mode.
3. TopHat 0 puts it in Arcade Drive
4. TopHat 4 puts it in Tank Drive
5. Tank Drive and Spinner Control overlap so you must put it in Arcade Drive to move the spinner without moving.
6. The code will likely need many changes to work with the USB Controller.
/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
Gripperbot - Remote Control
- NOTE: Gripperbot can be used to pick up game objects from the floor and to raise the flag.
- This program allows you to remotely control your robot using the XBox.
- This program also ignores low values that would cause your robot to move when the joysticks fail to
return back to exact center.  You may need to adjust the 'threshold' value to get it just right.

Robot Model(s): TETRIX Gripperbot (IR) (Virtual Worlds)

[I/O Port]          [Name]              [Type]                [Description]
Motor Port A        gripperMotor        NXT Motor             Gripper motor
Motor Port D        rightMotor          TETRIX Motor          Right side motor
Motor Port E				leftMotor						TETRIX Motor					Left side motor
Motor Port F 				armMotor						TETRIX Motor					Arm motor
Motor Port G 				spinnerMotor				TETRIX Motor 					Spinner motor

Sensor Port 2				IRSeeker						IRSeeker 1200					HiTechnic IRSeeker 1200
Sensor Port 3				light   						Light Sensor					NXT Light Sensor (Active)
Sensor Port 4				sonar 							Sonar Sensor					NXT Sonar Sensor
----------------------------------------------------------------------------------------------------*/

#pragma debuggerWindows("joystickSimple");
#include "JoystickDriver.c"

task main()
{
	//Integer variable that allows you to specify a "deadzone" where values (both positive or negative)
	//less than the threshold will be ignored.
	int threshold = 10;

	// If tankMode is true, then robot uses Tank Drive
	// If tankMode is false, then robot uses Arcade Drive
	bool tankMode = false;

	//Loop Forever
	while(1 == 1)
	{
		//Get the Latest joystick values
		getJoystickSettings(joystick);

		//Driving Control
		float topHat = joystick.joy1_TopHat;
		if(topHat == 0)     // XBox TopHat 0 (up)
			tankMode = true;
		if(topHat == 4)     // XBox TopHat 4 (down)
			tankMode = false;


		// XBox Left Analog Stick //
		float x1 = joystick.joy1_x1;
		float y1 = joystick.joy1_y1;

		// XBox Right Analog Stick //
		float x2 = joystick.joy1_x2;
		float y2 = joystick.joy1_y2;
		if(tankMode == false)
		{
			// Arcade Drive Uses Only Left Analog Stick //
			if(abs(x1) > threshold || abs(y1) > threshold)
			{
				x1 = x1*0.5;
				motor[leftMotor] = x1 + y1;
				motor[rightMotor] = -x1 + y1;
			}
			else
			{
				motor[leftMotor] = 0;
				motor[rightMotor] = 0;
			}
		}
		else
		{
			// Tank Drive Uses Both Left and Right Analog Sticks //
			if(abs(y1) > threshold)
				motor[leftMotor] = y1;
			else
				motor[leftMotor] = 0;

			if(abs(y2) > threshold)
				motor[rightMotor] = y2;
			else
				motor[rightMotor] = 0;
		}

		//Arm Motor Control
		if(joy1Btn(1) == 1)          // XBox A
		{
			motor[armMotor] = 35;      // raise the arm
		}
		else if(joy1Btn(2) == 1)     // XBox B
		{
			motor[armMotor] = -35;     // lower the arm
		}
		else
		{
			motor[armMotor] = 0;       // stop the arm.
		}

		//Gripper Motor Control
		if(joy1Btn(4) == 1)          // XBox Y
		{
			motor[gripperMotor] = 50;  // close the gripper
		}
		else if(joy1Btn(3) == 1)     // XBox X
		{
			motor[gripperMotor] = -50; // open the gripper
		}
		else
		{
			motor[gripperMotor] = 0;   // stop the gripper
		}

		//Spinner Motor Control
		// Note: In tank drive mode, you will notice the spinner spinning the whole time
		//       you use the right motor. Switch to Arcade Drive to use the spinner without moving.
		if(joystick.joy1_y2 > threshold) // XBox Right Analog Pushed Up
		{
			motor[spinnerMotor] = -75;     // raise the flag up with the spinner.
		}
		else if(joystick.joy1_y2 < -threshold) // XBox Right Analog Pushed Down
		{
			motor[spinnerMotor] = 75;      // lower the flag with the spinner.
		}
		else
		{
			motor[spinnerMotor] = 0;      // stop rotating the spinner.
		}

	}
}
